### PR TITLE
Added script to add data anlysis parameters to sdrf + extended maxquant script to include several of them

### PR DESCRIPTION
**Pull request by veitveit**

### CODE REVIEW

**Comment by ypriverol** [comment]
@veitveit cam you review the PR. It is failing the tests.

**Comment by veitveit** [comment]
@ypriverol Thanks, tried my best :-)

**Comment by veitveit** [comment]
@ypriverol I won't be able to fix the remaining issue (apparently a too complex loop) which might be due to too many if statements. There is now documentation whatsoever about how to fix that and it still pops up after cleaning up a bit.

**Comment by veitveit** [comment]
@ypriverol I made it :-)

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
