### PR TITLE
Add column name validation

### PR DESCRIPTION
**Pull request by levitsky**
This PR adds another level of validation: column names. It produces an error if unexpected columns are present. Right now the allowed columns are: `source name`, `assay name`, `material type` <s>(may be removed, pending discussion in https://github.com/bigbio/proteomics-metadata-standard/issues/272)</s>, as well as `comment` and `characteristics`.

**Warning: This version produces 4 validation errors on the current set of annotations, one of which is a whitespace issue and three are for a column named `description`.**

### CODE REVIEW

**Comment by levitsky** [comment]
Gotta check what happens with the test here, sorry. Never looked at what it does actually.

**Comment by levitsky** [comment]
Oh well, the test file also has a `description` column. Is it another undocumented part of the standard or should we remove it?

**Comment by levitsky** [comment]
Actually the current failure seems to have nothing to do with this PR. Running the test locally on `master` fails for me with the same error:

```
$ python sdrf_pipelines/tests/sdrfchecker_tests.py
Traceback (most recent call last):
File "sdrf_pipelines/tests/sdrfchecker_tests.py", line 39, in <module>
test_bioontologies()
File "sdrf_pipelines/tests/sdrfchecker_tests.py", line 22, in test_bioontologies
results = client.recommender(keyword, filters="ontologies:[nbcitaxon]")
File "/home/lev/py/sdrf-pipelines/sdrf_pipelines/zooma/zooma.py", line 79, in recommender
return self._zooma_api_request(full_url, 'get', payload)
File "/home/lev/py/sdrf-pipelines/sdrf_pipelines/zooma/zooma.py", line 92, in _zooma_api_request
json_response = r.json()
File "/home/lev/.virtualenvs/pride/lib/python3.8/site-packages/requests/models.py", line 898, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
The `test_validate_srdf()` function works fine.

**Comment by ypriverol** [comment]
This is probably a problem in EBI down Zooma.

**Pull request merged**
