### PR TITLE
Fixed some errors

### PR DESCRIPTION
**Pull request by daichengxin**

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Thanks for the quick fix I can test it today. Are there regression tests for the converters already? Would be a good idea.
Might have been better if the PRs for bug fixing and new features were separate but now it's ok. Probably not worth splitting.

**Comment by jpfeuffer** [comment]
Yes, so the old SDRF works again. Can be merged from my side, so we can continue working on our pipelines with the latest version. Still, regression tests would be great. I will also test the labelled experiments functionality today.
Do you plan to support mixed SDRFs or will SDRFs be split in that case?

**Comment by ypriverol** [comment]
@daichengxin remember to increase the version.

**Review by ypriverol — CHANGES_REQUESTED** [review]
@daichengxin : 
- [ ] remember to increase the version. 
- [ ] As @jpfeuffer said, we should add a test in the test folder that compare the conversion of OpenMS from SDRF with a manual annotated OpenMS configuration file.

**Pull request merged**
