### PR TITLE
Minor bug fixes

### PR DESCRIPTION
**Pull request by jgriss**
* Fixes TMT16 labels
  * Added nicer error message for missing labels

### CODE REVIEW

**Comment by jgriss** [comment]
@ypriverol If the changes are OK with you, I'd need a new release to update my Conda environment and continue working on the pipeline

**Comment by jgriss** [comment]
Or is there a way to add a GitHub package to the conda spec?

**Comment by ypriverol** [comment]
When we approve the PR we can increase the conda version.

**Comment by jgriss** [comment]
Great!

**Pull request closed without merging**
