### PR TITLE
Added new enzymes for OpenMS

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by ypriverol** [comment]
Can you share the enzyme.xml @jpfeuffer

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Enzymes.xml

**Comment by ypriverol** [comment]
do you think is better to read a file that hardcodes the map?

**Comment by jpfeuffer** [comment]
Doesn't matter much. Since you have to update the enzymes.xml anyway with each update. But it might avoid human errors.

**Comment by jpfeuffer** [comment]
Looks good. For unspecific cleavage there was special code? Or is it not supported yet?

**Comment by ypriverol** [comment]
@jpfeuffer can I merge this PR

**Review by jpfeuffer — APPROVED** [review]

**Pull request merged**
